name: condition.yml
on: push

jobs:
  deploiement:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : S'exécute à chaque fois
      - name: Simulation des tests
        run: echo "Test OK"

      # Étape 2 : S'exécute uniquement sur la branche main
      - name: Déploiement
        # La condition vérifie si la branche qui a déclenché le push est "main"
        if: github.ref == 'refs/heads/main'
        run: echo "Déploiement en cours..."